services:
  - type: web
    name: partner-backend
    runtime: java
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jdk
      mvn clean package -DskipTests
    startCommand: java -jar target/partner-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: PATH
        value: /usr/lib/jvm/java-17-openjdk-amd64/bin:${PATH}
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_REDIS_HOST
        sync: false
      - key: SPRING_REDIS_PORT
        sync: false
      - key: SPRING_REDIS_PASSWORD
        sync: false
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: SA_TOKEN_JWT_SECRET_KEY
        value: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY 