services:
  - type: web
    name: partner-backend
    runtime: docker
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jdk
      mvn clean package -DskipTests
    startCommand: java -jar target/partner-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: PATH
        value: /usr/lib/jvm/java-17-openjdk-amd64/bin:${PATH}
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/partner?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: 123456
      - key: SPRING_REDIS_HOST
        value: localhost
      - key: SPRING_REDIS_PORT
        value: 6379
      - key: SPRING_REDIS_PASSWORD
        value: ""
      - key: SPRING_MAIL_HOST
        value: smtp.qq.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        value: 1477129018@qq.com
      - key: SPRING_MAIL_PASSWORD
        value: qlmjfzjqvzjqiicd
      - key: TMDB_API_KEY
        value: 1ad3fcc3a67f178a8c8958896787f031
      - key: SA_TOKEN_JWT_SECRET_KEY
        value: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY 